import {
  Accessibility,
  Armchair,
  ArrowUpDown,
  Bath,
  Bed,
  BellRing,
  Car,
  CarTaxiFront,
  ChefHat,
  Circle,
  Coffee,
  Croissant,
  Dumbbell,
  Flame,
  Flower2,
  Footprints,
  Lock,
  Martini,
  MonitorPlay,
  Mountain,
  Microwave,
  PackageOpen,
  PanelTopOpen,
  Refrigerator,
  Shirt,
  ShowerHead,
  Speaker,
  Sparkles,
  Trees,
  Tv,
  UtensilsCrossed,
  Waves,
  Wifi,
  Wind,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export interface AmenityIconOption {
  value: string;
  label: string;
  icon: LucideIcon;
}

const amenityIconMap: Record<string, LucideIcon> = {
  accessibility: Accessibility,
  armchair: Armchair,
  'arrow-up-down': ArrowUpDown,
  bath: Bath,
  bed: Bed,
  'bell-ring': BellRing,
  car: Car,
  'car-taxi-front': CarTaxiFront,
  'chef-hat': ChefHat,
  coffee: Coffee,
  croissant: Croissant,
  dumbbell: Dumbbell,
  flame: Flame,
  'flower-2': Flower2,
  footprints: Footprints,
  lock: Lock,
  martini: Martini,
  'monitor-play': MonitorPlay,
  mountain: Mountain,
  microwave: Microwave,
  'package-open': PackageOpen,
  'panel-top-open': PanelTopOpen,
  refrigerator: Refrigerator,
  shirt: Shirt,
  'shower-head': ShowerHead,
  speaker: Speaker,
  sparkles: Sparkles,
  trees: Trees,
  tv: Tv,
  'utensils-crossed': UtensilsCrossed,
  waves: Waves,
  'waves-ladder': Waves,
  wifi: Wifi,
  wind: Wind,
};

export const amenityIconOptions: AmenityIconOption[] = [
  { value: 'wind', label: 'Vento / climatiza??o', icon: Wind },
  { value: 'flame', label: 'Calor / churrasqueira', icon: Flame },
  { value: 'tv', label: 'TV', icon: Tv },
  { value: 'refrigerator', label: 'Geladeira / frigobar', icon: Refrigerator },
  { value: 'lock', label: 'Cofre / seguran?a', icon: Lock },
  { value: 'panel-top-open', label: 'Varanda / abertura', icon: PanelTopOpen },
  { value: 'shirt', label: 'Roupa / lavanderia', icon: Shirt },
  { value: 'armchair', label: 'Mobili?rio', icon: Armchair },
  { value: 'bath', label: 'Banheira / banho', icon: Bath },
  { value: 'shower-head', label: 'Chuveiro', icon: ShowerHead },
  { value: 'footprints', label: 'Chinelos / spa', icon: Footprints },
  { value: 'package-open', label: 'Amenities / kit', icon: PackageOpen },
  { value: 'wifi', label: 'Wi?Fi', icon: Wifi },
  { value: 'monitor-play', label: 'Streaming / m?dia', icon: MonitorPlay },
  { value: 'speaker', label: 'Som ambiente', icon: Speaker },
  { value: 'chef-hat', label: 'Cozinha', icon: ChefHat },
  { value: 'microwave', label: 'Micro-ondas', icon: Microwave },
  { value: 'coffee', label: 'Cafeteira', icon: Coffee },
  { value: 'utensils-crossed', label: 'Restaurante / utens?lios', icon: UtensilsCrossed },
  { value: 'waves', label: 'Mar / piscina', icon: Waves },
  { value: 'mountain', label: 'Montanha', icon: Mountain },
  { value: 'trees', label: 'Jardim / ?rea verde', icon: Trees },
  { value: 'waves-ladder', label: 'Piscina privativa', icon: Waves },
  { value: 'flower-2', label: 'Jardim / flores', icon: Flower2 },
  { value: 'bell-ring', label: 'Servi?o de quarto', icon: BellRing },
  { value: 'croissant', label: 'Caf? da manh?', icon: Croissant },
  { value: 'car', label: 'Estacionamento', icon: Car },
  { value: 'dumbbell', label: 'Academia', icon: Dumbbell },
  { value: 'sparkles', label: 'Spa / premium', icon: Sparkles },
  { value: 'martini', label: 'Bar', icon: Martini },
  { value: 'car-taxi-front', label: 'Transfer', icon: CarTaxiFront },
  { value: 'accessibility', label: 'Acessibilidade', icon: Accessibility },
  { value: 'arrow-up-down', label: 'Elevador / mobilidade', icon: ArrowUpDown },
  { value: 'bed', label: 'Cama / enxoval', icon: Bed },
];

export function getAmenityIcon(iconName?: string | null): LucideIcon {
  if (!iconName) {
    return Circle;
  }

  return amenityIconMap[iconName] || Circle;
}
